@startuml
object "demo:phpDemo1" as dem  {
name = "php_demo1"
subfolders: ArrayList<Folder> = [Source Files, Include Path, Remote Files]
files: ArrayList<File> = []
}
object "sourcef:sourceFiles" as sf{
name = "Source Files"
subfolders: ArrayList<Folder> = [.phalcon, cache, public]
files: ArrayList<File> = []
}
object "path:includePath" as ip {
name = "Include Path"
subfolders: ArrayList<Folder> = []
files: ArrayList<File> = []
}
object "rmfiles:remoteFiles" as rf{
name = "Remote Files"
subfolders: ArrayList<Folder> = []
files: ArrayList<File> = []
}
object "phal:phalcon" as ph{
name = ".phalcon"
subfolders: ArrayList<Folder> = []
files: ArrayList<File> = []
}
object "caf:cache" as ch{
name = "cache"
subfolders: ArrayList<Folder> = []
files: ArrayList<File> = []
}
object "pub:public" as pb {
name = "public"
subfolders: ArrayList<Folder> = []
files: ArrayList<File> = [.htaccess, .htrouter.php, index.html]
}
object "hta:htaccess" as ht {
name = ".htaccess"
}
object "htr:htrouter" as hr {
name = ".htrouter.php"
}
object "ind:index" as id{
name = "index.html"
}
dem *-- sf : contains
dem *-- ip : contains
dem *-- rf : contains
sf *-- ph : contains
sf *-- ch : contains
sf *-- pb : contains
pb *-- ht : contains
pb *-- hr : contains
pb *-- id : contains
@enduml