@startuml

class Instructor {
    - String firstName
    - String lastName
    - String officeNumber
    + String getFirstName()
    + void setFirstName(String firstName)
    + String getLastName()
    + void setLastName(String lastName)
    + String getOfficeNumber()
    + void setOfficeNumber(String officeNumber)
    + toString()
}

class Textbook {
    - String title
    - String author
    - String publisher
    + String getTitle()
    + void setTitle(String title)
    + String getAuthor()
    + void setAuthor(String author)
    + String getPublisher()
    + void setPublisher(String publisher)
    + toString()
}

class Course {
    - String name
    - ArrayList<Instructor> instructors
    - ArrayList<Textbook> textbooks
    + Course()
    + String getName()
    + void setName(String name)
    + void addInstructor(Instructor instructor)
    + void removeInstructor(Instructor instructor)
    + ArrayList<Instructor> getInstructors()
    + void addTextbook(Textbook textbook)
    + void removeTextbook(Textbook textbook)
    + ArrayList<Textbook> getTextbooks()
    + toString()
    + void printCourse()
}

Instructor --o Course : "teaches"
Textbook --o Course : "refers"

@enduml
