@startuml
object "instructor1:Instructor" as i1 {
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "textbook:Textbook" as tb1 {
    title = "Clean Code"
    author = "Robert C. Martin"
    publisher = "Prentice Hall"
}

object Course {
    name = "Advanced Software Engineering"
}

Course o-- i1
Course o-- tb1
@enduml


